### ISSUE TITLE
<select> text is still black

### ISSUE THREAD

**Issue by FranklinYu** [overdodactyl/Stylus-Dark#3]
Default style of Stylish seems to treat `select` differently, so `#header select` doesn’t simply inherit from `#header`. Simply

```css
select {
    color: silver;
}
```

works.
